name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron:  '47 1 * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup JBang
        uses: jbangdev/setup-jbang@v0.1.0
      - name: version info
        run: jbang version --verbose
      - name: dump env
        run: jbang env@jbangdev || true
      - name: Run update script
        run: jbang --verbose update.java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit README and push
        uses: EndBug/add-and-commit@v7
        with:
          add: readme.adoc
          default_author: github_actions
          message: Automatically update README.adoc
